"use client";

import * as React from "react";
import { Accordion as AccordionPrimitive } from "radix-ui";
import { cn } from "@/lib/utils";

/**
 * Radix accordion, restyled for this design.
 *
 * Generated by the shadcn CLI, then corrected: it emitted `import { cn } from
 * "cn"` (which pulled an unrelated npm package of that name), a lucide chevron
 * we do not use, and theme tokens this project does not define. The design
 * calls for a gold plus that turns into a cross.
 */

function Accordion({
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Root>) {
  return <AccordionPrimitive.Root data-slot="accordion" {...props} />;
}

function AccordionItem({
  className,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Item>) {
  return (
    <AccordionPrimitive.Item
      data-slot="accordion-item"
      className={cn("border-b border-white/12", className)}
      {...props}
    />
  );
}

function AccordionTrigger({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Trigger>) {
  return (
    <AccordionPrimitive.Header className="flex">
      <AccordionPrimitive.Trigger
        data-slot="accordion-trigger"
        className={cn(
          // Radix wraps the trigger in an <h3>, so it picks up the display
          // face from the base heading rule. The design sets the questions in
          // the mono body face — override it here rather than weakening the
          // heading rule, which the rest of the page relies on.
          "group flex flex-1 items-center justify-between gap-6 py-[1.4em] text-left font-mono font-normal outline-none",
          className,
        )}
        {...props}
      >
        {children}
        <PlusCross />
      </AccordionPrimitive.Trigger>
    </AccordionPrimitive.Header>
  );
}

/** Plus that rotates into a cross when the item opens. */
function PlusCross() {
  return (
    <span
      aria-hidden
      className="relative block size-[1.9em] shrink-0 transition-transform duration-300 ease-out group-data-[state=open]:rotate-45"
    >
      <span className="absolute top-1/2 left-0 h-px w-full -translate-y-1/2 bg-gold" />
      <span className="absolute top-0 left-1/2 h-full w-px -translate-x-1/2 bg-gold" />
    </span>
  );
}

function AccordionContent({
  className,
  children,
  ...props
}: React.ComponentProps<typeof AccordionPrimitive.Content>) {
  return (
    <AccordionPrimitive.Content
      data-slot="accordion-content"
      className="overflow-hidden data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
      {...props}
    >
      <div className={cn("pb-[1.4em] text-white/65", className)}>{children}</div>
    </AccordionPrimitive.Content>
  );
}

export { Accordion, AccordionItem, AccordionTrigger, AccordionContent };
